gh-2335 Adding github workflow to automate koryphe version update.
gchq/Gaffer pull request #2344
Opened 2020-11-19 08:26 UTC by m29827

2020-11-19 08:31 UTC, m29827 commented
@d47853 This change is still using the updateKorypheVersion.sh script to perform the update. Happy to migrate the logic into the workflow but it might be useful to keep the script intact so it can be run outside of github.

2020-11-19 09:02 UTC, d47853 reviewed
Looks good. Although it might be worth automatically submitting a pull request if the version is upgraded.

2020-11-19 09:02 UTC, d47853 commented on .github/workflows/update-koryphe-version.yaml
> +      - name: Update Korpyhe Version
Could make the pull request afterwards?

2020-11-19 10:57 UTC, m29827 commented on .github/workflows/update-koryphe-version.yaml
> +      - name: Update Korpyhe Version
Now creating a PR.

2020-11-24 15:28 UTC, d47853 requested changes

2020-11-24 15:28 UTC, d47853 commented on .github/workflows/update-koryphe-version.yaml
> +          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
Don't think admin token would be required for this. You could use the default one:
```suggestion
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

2020-11-27 10:30 UTC, d47853 approved these changes

2020-12-01 12:51 UTC, merged