gc-2832 update ranged copyright statements
gchq/Gaffer pull request #2407
Opened 2021-04-06 13:48 UTC by javadev001001

Updated ranged copyright statements

2021-04-13 14:30 UTC, GCHQDev404 requested changes
ctrl-R is not a suitable solution.

2021-04-13 14:33 UTC, GCHQDev404 commented on core/access/src/main/java/uk/gov/gchq/gaffer/access/predicate/AccessPredicate.java
> + * Copyright 2021 Crown Copyright
This class was not made in 2021.

2021-05-06 07:09 UTC, hj325488 commented
Is the correct format for the copyright strings: "Copyright <year file created>-<year last modified> Crown Copyright"?

If so, I've written a small helper script that creates this information from the Git history. If this ticket isn't being worked on by anyone else at the moment, I could pick it up and finish it off.

2021-05-07 10:35 UTC, GCHQDev404 commented
@hj325488 
`Copyright [YYYY] Crown Copyright` first year
`"Copyright [First Year]-[Current Year] Crown Copyright"?` for following years

2021-06-03 09:57 UTC, GCHQDev404 commented
This PR has gone dormant and will be closed.

2021-06-10 09:23 UTC, GCHQDev404 commented
Dormant & incomplete.

2021-06-10 09:23 UTC, closed without merging

2021-06-10 09:28 UTC, GCHQDev404 commented
incorrect branch and issue labelling should be gh-2382 not gc-2832