gh-2559 added hasTrait, its handler and corresponding tests
gchq/Gaffer pull request #2561
Opened 2022-01-11 14:37 UTC by p3430233

2022-01-11 16:18 UTC, t92549 requested changes

2022-01-11 16:18 UTC, t92549 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandlerTest.java
> +        assertTrue(actual);
Could add some tests where answer will be false (test that it doesn't have a trait it shouldn't have)

2022-01-11 16:18 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
> +import uk.gov.gchq.gaffer.store.operation.*;
This will fail on checkstyle

2022-01-12 15:54 UTC, t11947 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/HasTrait.java
> +     * The currentTraits holds a boolean value, which if false
Would it be useful to change this comment to reflect that it isn't used for returning a full list of supported traits for this operation but rather just comparing against either the store default or the schema current traits?

2022-01-12 15:54 UTC, t11947 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandlerTest.java
> +                        .currentTraits(true)
Could be worth adding tests to confirm currentTraits flag works as intended?

2022-01-13 15:52 UTC, t11947 approved these changes

2022-01-13 16:04 UTC, t92549 requested changes

2022-01-13 16:04 UTC, t92549 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandlerTest.java
> +                new HasTrait.Builder()
Could use hasStoreTrait helper function here too

2022-01-13 16:04 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
> +import uk.gov.gchq.gaffer.store.operation.*;
This needs changing

2022-01-13 16:04 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
> +import uk.gov.gchq.gaffer.store.operation.handler.*;
This also needs to be every import for checkstyle

2022-01-14 14:07 UTC, t92549 approved these changes

2022-01-14 14:07 UTC, merged