gh-2573: Replace hasTrait usages with Operation
gchq/Gaffer pull request #2574
Opened 2022-01-18 22:17 UTC by t92549

2022-01-20 18:49 UTC, GCHQDev404 commented
You considered creating a static util method somewhere ?

``` java
public static boolean hasTrait(Trait trait){
boolean isDynamic;
                 try {
                     isDynamic = graph.execute(new HasTrait.Builder()
                             .trait(trait)
                             .currentTraits(false)
                             .build(), new Context());
                 } catch (final OperationException e) {
                     throw new GafferRuntimeException("Error performing HasTrait Operation while validating Views in OperationChain.", e);
                 }               
return isDynamic 
 ```

2022-01-21 12:08 UTC, t92549 commented
@GCHQDev404 could do but maybe seems silly to replace a function with an Operation called by a function, only used 4 times anyway.

2022-01-25 11:06 UTC, GCHQDev404 requested changes

2022-01-25 11:06 UTC, GCHQDev404 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +                .filter(t -> !accTraitsIsCurrent.contains(t)).collect(Collectors.toSet());
👎  You've inserted a lot of line wrap which makes spot the difference harder to see for these tests in future.
```
xxxxx xxxx xx MapTraits xxxx xxx x xx
xxxxx xxxx xx AccTraits xxxx xxx x xx
```

2022-01-25 11:06 UTC, GCHQDev404 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +        assertEquals(ACC_CURRENT_TRAITS, accTraitsIsCurrent,
👎  You've inserted a lot of line wrap which makes spot the difference harder to see for these tests in future.
```
xxxxx xxxx xx MapTraits xxxx xxx x xx
xxxxx xxxx xx AccTraits xxxx xxx x xx
```

2022-01-25 11:06 UTC, GCHQDev404 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +        final Set<StoreTrait> mapTraitsIsCurrent = map.getGraph().execute(getTraits, testUser);
You inserted a lot line wrap in tests

2022-01-25 11:06 UTC, GCHQDev404 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreGetTraitsTest.java
> +    private static final FederatedAccess ACCESS_UNUSED_AUTH_AND_USER = new FederatedAccess(
👎 line wrapping here makes it a smidge harder to spot the difference between the different FederatedAccess. 
We have bigger monitors these days.

```
xxx x xx xx xxxxx xxxx xxxxxxxx UNUSED_AUTH_STRING xxxxxx
xxx x xx xx xxxxx xxxx xxxxxxxx TEST_USER_ID xxxxxx
```

2022-01-25 11:10 UTC, t92549 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/StoreTest.java
> +        when(schemaOptimiser.optimise(any(Schema.class), any(Boolean.class))).then(returnsFirstArg());
It was mocked before I just changed how it was done

2022-01-25 11:13 UTC, t92549 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +            Sets.newHashSet(UNUSED_AUTH_STRING), UNUSED_AUTH_STRING);
This was cherry picked from 2553 so I suggest for merging purposes this stays how it is then you raise that issue with 2553 when it comes to being merged? Or I can change it here and ask that 2553 merges my changes into their branch?

2022-01-25 11:14 UTC, t92549 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +        CacheServiceLoader.shutdown();
Haha no idea

2022-01-25 11:15 UTC, t92549 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +        CacheServiceLoader.shutdown();
Without this it works locally when running just some of the tests but not on GitHub

2022-01-25 11:17 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandler.java
> +                .options(isNull(operation.getOptions()) ? new HashMap<>() : new HashMap<>(operation.getOptions()))
Yeah maybe, I just copied from here: https://github.com/gchq/Gaffer/blob/f54e069c27a61587e54f6406697ad9a4a726d88b/store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/handler/impl/FederatedGetTraitsHandler.java#L55

it needs to copy some of the options but I guess the loop one probably not?

2022-01-25 12:10 UTC, t92549 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedGraphStorageTraitsTest.java
> +            Sets.newHashSet(UNUSED_AUTH_STRING), UNUSED_AUTH_STRING);
Have reverted this cherry pick and added my own manual fix which only clears the cache in the broken test

2022-01-25 12:22 UTC, GCHQDev404 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandler.java
> +                .options(isNull(operation.getOptions()) ? new HashMap<>() : new HashMap<>(operation.getOptions()))
In `FederatedGetTraitsHandler` the wrapping is trying to be kinda be same operation but just federated it.
In the above your asking a new operation and then using result for your own answer.

This raises the alarm that possibly :( all operations need to be checked with the FederatedStore for incorrect looping.

2022-01-28 11:15 UTC, GCHQDev404 approved these changes

2022-01-28 12:16 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandler.java
> +                .options(isNull(operation.getOptions()) ? new HashMap<>() : new HashMap<>(operation.getOptions()))
This was resolved for the time being by adding a check: https://github.com/gchq/Gaffer/blob/40bb337d2ca91fea2dadcd04cddec46021c169ee/core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/HasTraitHandler.java#L35-L44

2022-01-28 15:00 UTC, GCHQDev404 requested changes
Possible Issue with store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChainValidator.java

2022-01-28 18:04 UTC, t92549 commented on store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/operation/FederatedOperationChainValidator.java
> +                if (!graph.getStoreTraits().contains(StoreTrait.DYNAMIC_SCHEMA)) {
Note: This should be fixed by https://github.com/gchq/Gaffer/issues/2580

2022-01-28 18:04 UTC, t92549 commented on store-implementation/federated-store/src/main/java/uk/gov/gchq/gaffer/federatedstore/util/FederatedStoreUtil.java
> +                    } else if (!graph.getStoreTraits().contains(StoreTrait.DYNAMIC_SCHEMA)) {
Note: This should be fixed by https://github.com/gchq/Gaffer/issues/2580

2022-01-28 18:04 UTC, merged