Generic operation handler update
gchq/Gaffer pull request #2593
Opened 2022-03-01 19:30 UTC by r32575

Convert handlers to the new [Maestro](https://github.com/gchq/Maestro) format

2022-03-01 23:14 UTC, GCHQDev404 commented on store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
> +    private static final String INPUT = "input";
input isn't required.

2022-03-02 00:04 UTC, GCHQDev404 requested changes

2022-03-02 00:04 UTC, GCHQDev404 commented on store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
> +    private static final String INPUT = "input";
No longer required.
If you Pull my branch update into yours.

2022-03-02 00:04 UTC, GCHQDev404 commented on store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
> +                .fieldRequired(INPUT, Iterable.class)
If you Pull my branch update into yours.
.inputRequired(Iterable.class)

2022-03-02 11:43 UTC, r32575 commented on store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
> +                .inputRequired(Iterable.class)
Changed to `inputRequired`

2022-03-02 11:44 UTC, r32575 commented on store-implementation/accumulo-store/src/main/java/uk/gov/gchq/gaffer/accumulostore/operation/handler/AddElementsHandler.java
> +    static class OperationBuilder extends BuilderSpecificInputOperation<OperationBuilder, AddElementsHandler> {
Added the builder... Do the methods look okay?

2022-03-02 14:27 UTC, GCHQDev404 approved these changes

2022-03-02 14:29 UTC, merged