gh-2723 Split ImportCsv into two parts, refactor CsvElementGenerator
gchq/Gaffer pull request #2778
Opened 2022-10-18 16:20 UTC by p3430233

2022-10-24 15:20 UTC, t92549 requested changes

2022-10-24 15:20 UTC, t92549 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/imprt/localfile/ImportFromLocalFile.java
> + * Copyright 2016-2020 Crown Copyright
Incidental change

2022-10-24 15:20 UTC, t92549 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/imprt/localfile/ImportFromLocalFile.java
> +@Since("1.0.0")
Should be 2.0.0

2022-10-24 15:20 UTC, t92549 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/imprt/localfile/ImportFromLocalFile.java
> +    public void setKey(final String key) {
This could be private to encourage use of `filePath`

2022-10-24 15:20 UTC, t92549 commented on core/operation/src/test/java/uk/gov/gchq/gaffer/operation/imprt/localfile/ImportFromLocalFileTest.java
> +        assertThat(FILE_PATH).isEqualTo(deserialisedOp.getKey());
This should be `getFilePath` (same for rest of file)

2022-10-24 15:20 UTC, t92549 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/operation/handler/export/localfile/ImportFromLocalFileHandler.java
> +    protected Iterable<?> getExport(final ImportFromLocalFile imprt, final LocalFileExporter exporter) throws OperationException {
Typo `imprt`

2022-10-24 15:20 UTC, t92549 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/imprt/localfile/ImportFromLocalFileHandlerTest.java
> +                .key(FILE_PATH)
This should be `filePath`

2022-10-26 15:54 UTC, t92549 commented
PR is failing on spotless checks

2022-11-15 08:53 UTC, GCHQDeveloper314 requested changes

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvElementGenerator.java
> +        //List<String> elementColumnNames = ImmutableList.of(csvFormat.getVertex(), csvFormat.getEntityGroup(), csvFormat.getEdgeGroup(), csvFormat.getSource(), csvFormat.getDestination());
Commented out line

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvElementGenerator.java
> +        private CsvFormat csvFormat;
I think these should all be together.

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/data/src/test/java/uk/gov/gchq/gaffer/data/generator/CsvElementGeneratorTest.java
> +        assertThat(expectedMessage).isEqualTo(actualMessage);
Can use AssertJ here to simplify the test. You'll need to change the imports as well (they will then be AssertJ only).
```suggestion

        //Then
        assertThatThrownBy(() -> generator.apply(lines))
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("Unsupported Type: Array");
```

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/add/CsvToElements.java
>  @Summary("Adds elements from a openCypher CSV file")
Is this right? The class is called `CsvToElements` and not `openCypherCsvToElements`.

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/export/localfile/LocalFileExporter.java
> +                fileToBeRead = StreamUtil.openStream(LocalFileExporter.class, filePath);
It would be better to use one of `FileUtils` or `StreamUtil` in this class and not both.

2022-11-15 08:53 UTC, GCHQDeveloper314 commented on core/store/src/main/java/uk/gov/gchq/gaffer/store/Store.java
> +        addOperationHandler(ImportFromLocalFile.class, new ImportFromLocalFileHandler());
I don't think these should be here at all. These shouldn't be core operations, the user/admin should need to have actively enabled them before they can be used.

2022-11-18 11:58 UTC, t92549 requested changes

2022-11-18 11:58 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvElementGenerator.java
> +@Summary("Generates elements from an  CSV string")
```suggestion
@Summary("Generates elements from a CSV string")
```

2022-11-18 11:58 UTC, t92549 commented on core/operation/src/main/java/uk/gov/gchq/gaffer/operation/impl/add/CsvToElements.java
> + * An {@code CsvToElements} operation will generate elements from a String input given a {@link CsvFormat}.
```suggestion
 * A {@code CsvToElements} operation will generate elements from a String input given a {@link CsvFormat}.
```

2022-11-18 13:29 UTC, t92549 submitted a review, later dismissed

2022-11-21 14:22 UTC, GCHQDeveloper314 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/add/CsvToElementsHandlerTest.java
> +                .hasMessageContaining("CsvToElements operation requires the user to provide a supported CsvFormat");
Not sure about this indenting.

2022-11-21 14:22 UTC, GCHQDeveloper314 approved these changes

2022-11-23 12:21 UTC, GCHQDeveloper314 approved these changes

2022-11-23 12:48 UTC, merged