Gh 2873: Refactor csv ImportExport
gchq/Gaffer pull request #2943
Opened 2023-04-25 16:08 UTC by t92549

2023-04-26 08:21 UTC, GCHQDeveloper314 reviewed
Wasn't there a problem with a test related to this where it wasn't testing anything? If that was this file and that's now fixed then that's good.

It looks like the issue has more in scope than just this change?

2023-04-26 09:02 UTC, t92549 commented
@GCHQDeveloper314 Yeah that has been fixed since. This PR is still is WIP, just wanted to make sure tests were passing

2023-05-10 09:07 UTC, GCHQDeveloper314 requested changes
It's not clear enough which are used to export from Gaffer and which for importing into Gaffer, this can be helped by adding Javadoc.

Do these changes to how CSV things are done require an update to the documentation?

2023-05-10 09:07 UTC, GCHQDeveloper314 commented on core/operation/src/test/java/uk/gov/gchq/gaffer/export/LocalFileExporterTest.java
>      public void setUp() {
```suggestion
    @BeforeEach
    public void setUp(@TempDir Path tempDir) {
```

2023-05-10 09:07 UTC, GCHQDeveloper314 commented on core/store/src/test/java/uk/gov/gchq/gaffer/store/operation/handler/export/localfile/ExportToLocalFileHandlerTest.java
>      public void setUp() {
```suggestion
    @BeforeEach
    public void setUp(@TempDir Path tempDir) {
```

2023-05-10 11:43 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
>      public static final String COMMA = ",";
It is used in child classes like `Neo4jCsvGenerator`: https://github.com/gchq/Gaffer/blob/94c2c615683068d3783ac421cfa442ce750557be/core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvGenerator.java#L59

2023-05-10 11:45 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
>      public static final String COMMA = ",";
Should maybe even be public?

2023-05-10 11:48 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvElementGenerator.java
> +@Summary("Generates elements from a Neo4j CSV")
I will add javadoc and remove the summary, but now I think about it, it would be nice if the generators did have a similar details endpoint

2023-05-10 12:40 UTC, GCHQDeveloper314 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
>      public static final String COMMA = ",";
Hmm, I meant to highlight just `public static final String COMMA = ","`, but as that was not part of this PR GitHub has marked the lines above as well. Those should be `protected` and don't need to be changed.

2023-05-10 16:03 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvElementGenerator.java
> +@Summary("Generates elements from a Neo4j CSV")
I added some javadoc, but what do you think in terms of clarity?

2023-05-10 16:05 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/CsvGenerator.java
>      public static final String COMMA = ",";
I see! Have made that private too

2023-05-11 07:35 UTC, GCHQDeveloper314 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvElementGenerator.java
> +@Summary("Generates elements from a Neo4j CSV")
Javadoc is good, but I'm not sure about the `@Summary` which doesn't have a use.

2023-05-11 09:33 UTC, t92549 commented on core/data/src/main/java/uk/gov/gchq/gaffer/data/generator/Neo4jCsvElementGenerator.java
> +@Summary("Generates elements from a Neo4j CSV")
It could be used in niche scenarios and doesn't hurt to leave it in

2023-05-11 09:34 UTC, GCHQDeveloper314 approved these changes

2023-05-11 09:37 UTC, merged