Gh-3042: Tidy FederatedStoreVisibilityTest
gchq/Gaffer pull request #3043
Opened 2023-10-18 15:49 UTC by t92549

2023-10-19 08:25 UTC, GCHQDeveloper314 requested changes

2023-10-19 08:25 UTC, GCHQDeveloper314 commented on store-implementation/federated-store/src/test/java/uk/gov/gchq/gaffer/federatedstore/FederatedStoreVisibilityTest.java
> +    private static final User USER = new User.Builder().dataAuth(PUBLIC).build();
The two which are public can simply be private as they are not used outside this file. The line breaks between these fields can then be removed entirely.

2023-10-19 09:47 UTC, GCHQDeveloper314 approved these changes

2023-10-24 08:37 UTC, GCHQDeveloper314 approved these changes

2023-10-25 09:19 UTC, tb06904 approved these changes

2023-10-26 13:59 UTC, merged